name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Run unit tests
      run: dotnet test --configuration Release --logger trx --results-directory TestResults
      env:
        SOLUTION: WordsCountingApp.sln

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: TestResults